-- ============================================
-- MYSQL DATABASE SCHEMA
-- Database: maddasys_milk_collection_pwa
-- ============================================

-- 1. Create approved_devices table
CREATE TABLE IF NOT EXISTS approved_devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  device_fingerprint VARCHAR(255) NOT NULL UNIQUE,
  user_id VARCHAR(50) NOT NULL,
  approved BOOLEAN DEFAULT FALSE,
  device_info VARCHAR(255) DEFAULT NULL,
  last_sync TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_device_fingerprint (device_fingerprint),
  INDEX idx_user_id (user_id),
  INDEX idx_approved (approved)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Create farmers table
CREATE TABLE IF NOT EXISTS farmers (
  farmer_id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  route VARCHAR(100) NOT NULL,
  route_name VARCHAR(255) DEFAULT NULL,
  member_route VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_name (name),
  INDEX idx_route (route)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Create milk_collection table
CREATE TABLE IF NOT EXISTS milk_collection (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reference_no VARCHAR(100) UNIQUE NOT NULL,
  farmer_id VARCHAR(50) NOT NULL,
  farmer_name VARCHAR(255) DEFAULT NULL,
  session ENUM('AM', 'PM') NOT NULL,
  route_name VARCHAR(255) DEFAULT NULL,
  weight DECIMAL(10,2) NOT NULL,
  clerk_name VARCHAR(100) DEFAULT NULL,
  price_per_liter DECIMAL(10,2) NOT NULL,
  total_amount DECIMAL(10,2) GENERATED ALWAYS AS (weight * price_per_liter) STORED,
  collection_date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (farmer_id) REFERENCES farmers(farmer_id) ON DELETE CASCADE,
  INDEX idx_farmer_id (farmer_id),
  INDEX idx_session (session),
  INDEX idx_collection_date (collection_date),
  INDEX idx_reference (reference_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- NOTES:
-- ============================================
-- 1. device_fingerprint: Unique hash generated by frontend for device identification
-- 2. id: Auto-increment primary key managed by MySQL
-- 3. Backend returns the auto-generated 'id' when registering a device
-- 4. Frontend uses 'device_fingerprint' for device lookup
-- 5. All timestamps use MySQL's CURRENT_TIMESTAMP for compatibility
-- ============================================
